ShopSnowboardEquip/Controllers/EquipmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopSnowboardEquip.Data;
using ShopSnowboardEquip.Data.interfaces;
using ShopSnowboardEquip.Models;
using ShopSnowboardEquip.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopSnowboardEquip.Controllers
{
	public class EquipmentController : Controller

    {
		private readonly ICategoryRepository _categoryRepository;
		private readonly IEquipmentRepository _equipmentRepository;
		private readonly IGenderRepository _genderRepository;
	    private readonly AppDbContext _context;


        public EquipmentController(AppDbContext context, ICategoryRepository categoryRepository, IEquipmentRepository equipmentRepository, IGenderRepository genderRepository)
		{
			_categoryRepository = categoryRepository;
			_equipmentRepository = equipmentRepository;
            _genderRepository = genderRepository;
            _context = context;
        }

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Equipment> equipments;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                equipments = _equipmentRepository.Equipments.OrderBy(p => p.EquipmentId);
                currentCategory = "All equipments";
            }
            else
            {
                if (string.Equals("SnowAccessories", _category, StringComparison.OrdinalIgnoreCase))
                    equipments = _equipmentRepository.Equipments.Where(p => p.Category.CategoryName.Equals("SnowAccessories")).OrderBy(p => p.Name);
                else
                    equipments = _equipmentRepository.Equipments.Where(p => p.Category.CategoryName.Equals("SnowOutfit")).OrderBy(p => p.Name);

                currentCategory = _category;
            }

            return View(new EquipmentListViewModel
            {
                Equipment = equipments,
                CurrentCategory = currentCategory
            });
        }

		[Authorize(Roles = "Admin")]
		// GET: Equipments
		public async Task<IActionResult> Index()
		{
			var appDbContext = _context.Equipments.Include(e => e.Category).Include(e => e.Gender);
			return View(await appDbContext.ToListAsync());
		}

		// GET: Equipments/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var equipment = await _context.Equipments
				.Include(e => e.Category)
				.Include(e => e.Gender)
				.FirstOrDefaultAsync(m => m.EquipmentId == id);
			if (equipment == null)
			{
				return NotFound();
			}

			return View(equipment);
		}

		[Authorize(Roles = "Admin")]
		// GET: Equipments/Create
		public IActionResult Create()
		{
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId");
			ViewData["GenderId"] = new SelectList(_context.Genders, "GenderId", "GenderId");
			return View();
		}

		// POST: Equipments/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("EquipmentId,Name,ShortDescription,LongDescription,Price,ImageUrl,ImageThumbnailUrl,IsPreferredEquipment,InStock,CategoryId,GenderId")] Equipment equipment)
		{
			if (ModelState.IsValid)
			{
				_context.Add(equipment);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", equipment.CategoryId);
			ViewData["GenderId"] = new SelectList(_context.Genders, "GenderId", "GenderId", equipment.GenderId);
			return View(equipment);
		}
		[Authorize(Roles = "Admin")]
		// GET: Equipments/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var equipment = await _context.Equipments.FindAsync(id);
			if (equipment == null)
			{
				return NotFound();
			}
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", equipment.CategoryId);
			ViewData["GenderId"] = new SelectList(_context.Genders, "GenderId", "GenderId", equipment.GenderId);
			return View(equipment);
		}

		// POST: Equipments/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int EquipmentId, [Bind("EquipmentId,Name,ShortDescription,LongDescription,Price,ImageUrl,ImageThumbnailUrl,IsPreferredEquipment,InStock,CategoryId,GenderId")] Equipment equipment)
		{
			if (EquipmentId != equipment.EquipmentId)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(equipment);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!EquipmentExists(equipment.EquipmentId))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", equipment.CategoryId);
			ViewData["GenderId"] = new SelectList(_context.Genders, "GenderId", "GenderId", equipment.GenderId);
			return View(equipment);
		}
		[Authorize(Roles = "Admin")]
		// GET: Equipments/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var equipment = await _context.Equipments
				.Include(e => e.Category)
				.Include(e => e.Gender)
				.FirstOrDefaultAsync(m => m.EquipmentId == id);
			if (equipment == null)
			{
				return NotFound();
			}

			return View(equipment);
		}

		// POST: Equipments/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int EquipmentId)
		{
			var equipment = await _context.Equipments.FindAsync(EquipmentId);
			_context.Equipments.Remove(equipment);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool EquipmentExists(int id)
		{
			return _context.Equipments.Any(e => e.EquipmentId == id);
		}
	}
}

ShopSnowboardEquip/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopSnowboardEquip.Data.interfaces;
using ShopSnowboardEquip.Data.Models;
using ShopSnowboardEquip.ViewModels;

namespace ShopSnowboardEquip.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IEquipmentRepository _equipmentRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IEquipmentRepository equipmentRepository, ShoppingCart shoppingCart)
        {
            _equipmentRepository = equipmentRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int equipmentId)
        {
            var selectedEquipment = _equipmentRepository.Equipments.FirstOrDefault(p => p.EquipmentId == equipmentId);
            if (selectedEquipment != null)
            {
                _shoppingCart.AddToCart(selectedEquipment, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int equipmentId)
        {
            var selectedEquipment = _equipmentRepository.Equipments.FirstOrDefault(p => p.EquipmentId == equipmentId);
            if (selectedEquipment != null)
            {
                _shoppingCart.RemoveFromCart(selectedEquipment);
            }
            return RedirectToAction("Index");
        }
    }
}

ShopSnowboardEquip/Views/Shared/Carousel.cshtml
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <div class="poze-galerie">
        <div class="carousel-inner" role="listbox">

            <div class="item active">
                <img src="~/images/snow.jpg" alt="ASP.NET" class="img-responsive" />
            </div>
            <div class="item">
                <img src="~/images/snowboard.jpg" alt="Visual Studio" class="img-responsive" />
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

ShopSnowboardEquip/Views/Shared/EquipmentSummary.cshtml
@model Equipment

<div class="col-sm-4 col-lg-4 col-md-4">
	<div class="thumbnail">
		<img src="@Model.ImageThumbnailUrl" alt="" />
		<div class="caption">
			<h3 class="pull-right">@Model.Price.ToString("c")</h3>
			<h3>
				<a>@Model.Name</a>
			</h3>
			<p>@Model.ShortDescription</p>
            @*<p>@Model.GenderId</p>*@
		</div>
		<div class="addToCart text-right">
			<p class="button">
				<a class="btn btn-success" id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-equipmentId="@Model.EquipmentId">
					Add to cart
				</a>
			</p>
		</div>
	</div>
</div>

ShopSnowboardEquip/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
	<form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
		  method="post" class="navbar-right">
		<ul class="nav navbar-nav navbar-right">
			<li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
		</ul>
	</form>
}
else
{
	<ul class="nav navbar-nav navbar-right">
		<li><a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
		<li><a id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
	</ul>
}

ShopSnowboardEquip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopSnowboardEquip</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ShopSnowboardEquip</a>
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav mr-auto">
					<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
					@await Component.InvokeAsync("CategoryChoice")
					<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a></li>
					@await Component.InvokeAsync("ShoppingCartSummary")
					@await Html.PartialAsync("LoginPartial")

					<li>
						@if (User.Identity.IsAuthenticated)
						{
							if (User.IsInRole("Admin"))
							{
								<a asp-area="" asp-controller="Equipment" asp-action="Index">Manage Products</a>
							}
						}
					</li>

				</ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ShopSnowboardEquip</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>